# Generated by Django 5.1.7 on 2025-05-03 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='工作流定义的唯一名称', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('definition_json', models.JSONField(help_text='工作流图的 JSON 表示')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, help_text='此定义是否可用于启动新实例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作流定义',
                'verbose_name_plural': '工作流定义',
                'ordering': ('name', '-version'),
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '运行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELED', '已取消'), ('SUSPENDED', '已暂停')], default='PENDING', max_length=20, verbose_name='状态')),
                ('payload', models.JSONField(default=dict, help_text='此工作流实例的数据负载', verbose_name='数据负载')),
                ('current_node_ids', models.JSONField(default=list, help_text='定义中活动节点的 ID 列表', verbose_name='当前节点ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='触发对象ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='触发对象类型')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowdefinition', verbose_name='关联定义')),
            ],
            options={
                'verbose_name': '工作流实例',
                'verbose_name_plural': '工作流实例',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(help_text='来自工作流定义的节点 ID', max_length=255, verbose_name='节点 ID')),
                ('task_type', models.CharField(default='APPROVAL', help_text='任务类型，例如 APPROVAL, FORM_ENTRY', max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('ASSIGNED', '已分配'), ('COMPLETED', '已完成'), ('CANCELED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('assignee_type', models.CharField(choices=[('USER', '特定用户'), ('ROLE', '角色/用户组'), ('RULE', '规则指定')], max_length=20, verbose_name='指派类型')),
                ('assignee_identifier', models.CharField(help_text='用户 ID、角色名称或规则标识符', max_length=255, verbose_name='指派标识')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('outcome', models.CharField(blank=True, max_length=100, null=True, verbose_name='结果')),
                ('completion_data', models.JSONField(blank=True, null=True, verbose_name='完成数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='已分配用户')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflows.workflowinstance', verbose_name='关联实例')),
            ],
            options={
                'verbose_name': '工作流任务',
                'verbose_name_plural': '工作流任务',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(blank=True, help_text='相关的节点 ID，如果适用', max_length=255, null=True, verbose_name='节点 ID')),
                ('event_type', models.CharField(choices=[('INSTANCE_STARTED', '实例已启动'), ('INSTANCE_COMPLETED', '实例已完成'), ('INSTANCE_FAILED', '实例失败'), ('INSTANCE_CANCELED', '实例已取消'), ('NODE_ENTERED', '进入节点'), ('NODE_EXITED', '离开节点'), ('TASK_CREATED', '任务已创建'), ('TASK_ASSIGNED', '任务已分配/认领'), ('TASK_COMPLETED', '任务已完成'), ('TASK_TIMED_OUT', '任务超时'), ('COMMENT_ADDED', '评论已添加')], max_length=30, verbose_name='事件类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='详情')),
                ('user', models.ForeignKey(blank=True, help_text='触发事件的用户，如果适用', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='workflows.workflowinstance', verbose_name='关联实例')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_logs', to='workflows.workflowtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '工作流历史',
                'verbose_name_plural': '工作流历史',
                'ordering': ('timestamp',),
            },
        ),
    ]
