# Generated by Django 5.1.7 on 2025-04-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_digit_insert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': '员工档案', 'verbose_name_plural': '员工档案'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='employee',
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='薪酬金额(元)'),
        ),
        migrations.CreateModel(
            name='MessageEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeeprofile', verbose_name='接收员工')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.message', verbose_name='消息ID')),
            ],
            options={
                'unique_together': {('message', 'employee')},
            },
        ),
    ]
