# Generated by Django 5.1.7 on 2025-04-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': '审批记录', 'verbose_name_plural': '审批记录'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息通知', 'verbose_name_plural': '消息通知'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位信息', 'verbose_name_plural': '职位信息'},
        ),
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'verbose_name': '任务分配', 'verbose_name_plural': '任务分配'},
        ),
    ]
