# Generated by Django 5.1.7 on 2025-04-08 07:27

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employeeprofile', verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=18, validators=[myapp.models.validate_id_number_unique_if_not_empty], verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employeeprofile', verbose_name='关联员工'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employeeprofile', verbose_name='关联员工'),
        ),
    ]
