# Generated by Django 5.1.7 on 2025-04-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_approval_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_Power',
            fields=[
                ('power_id', models.AutoField(primary_key=True, serialize=False, verbose_name='权限ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('power_level', models.IntegerField(default=0, verbose_name='权限值')),
                ('modifie_same_department_position', models.BooleanField(default=False, verbose_name='是否允许修改同部门')),
                ('modifie_other_department_position', models.BooleanField(default=False, verbose_name='是否允许修改其他部门')),
            ],
            options={
                'verbose_name': '职位权限',
                'verbose_name_plural': '职位权限',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.position_power', verbose_name='职位权限'),
        ),
    ]
