# Generated by Django 5.1.7 on 2025-04-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_position_power_position_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave', models.FloatField(default=0, verbose_name='年假剩余天数')),
                ('sick_leave', models.FloatField(default=0, verbose_name='病假剩余天数')),
                ('personal_leave', models.FloatField(default=0, verbose_name='事假剩余天数')),
                ('marriage_leave', models.FloatField(default=0, verbose_name='婚假剩余天数')),
                ('maternity_leave', models.FloatField(default=0, verbose_name='产假剩余天数')),
                ('paternity_leave', models.FloatField(default=0, verbose_name='陪产假剩余天数')),
                ('bereavement_leave', models.FloatField(default=0, verbose_name='丧假剩余天数')),
                ('year', models.IntegerField(default=2025, verbose_name='年份')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='myapp.employeeprofile', verbose_name='关联员工')),
            ],
            options={
                'verbose_name': '剩余假期',
                'verbose_name_plural': '剩余假期',
                'indexes': [models.Index(fields=['employee'], name='myapp_leave_employe_8deda3_idx'), models.Index(fields=['year'], name='myapp_leave_year_611e98_idx')],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申请ID')),
                ('leave_type', models.CharField(choices=[('annual', '年假'), ('sick', '病假'), ('personal', '事假'), ('marriage', '婚假'), ('maternity', '产假'), ('paternity', '陪产假'), ('bereavement', '丧假'), ('other', '其他')], max_length=20, verbose_name='假期类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('days', models.FloatField(verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='myapp.employeeprofile', verbose_name='审批人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department', verbose_name='所属部门')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='myapp.employeeprofile', verbose_name='申请员工')),
            ],
            options={
                'verbose_name': '假期申请',
                'verbose_name_plural': '假期申请',
                'indexes': [models.Index(fields=['employee'], name='myapp_leave_employe_34a708_idx'), models.Index(fields=['department'], name='myapp_leave_departm_c3dba2_idx'), models.Index(fields=['status'], name='myapp_leave_status_e141bd_idx'), models.Index(fields=['start_date'], name='myapp_leave_start_d_7016a5_idx'), models.Index(fields=['end_date'], name='myapp_leave_end_dat_d3dea6_idx')],
            },
        ),
    ]
